### ISSUE TITLE
SSL Certificate has expired

### ISSUE THREAD

**Issue by rorymbyrne** [agrabeli/Project#7]
Website viewed via Chrome shows SSL Cert has expired.

<img width="1456" alt="screen shot 2016-08-17 at 21 04 31" src="https://cloud.githubusercontent.com/assets/18581795/17751246/3232dd9e-64be-11e6-89ff-f4bda13aeeb3.png">

**Comment by hellais** [comment]
Thanks for reporting this, I forgot to set the auto-renew cronjob on the cert. It's now renewed and will happen automatically.
